name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "tag=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}/wikiguesser:${{ env.tag }} .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 ${{ secrets.DOCKER_REPOSITORY }}/wikiguesser:${{ env.tag }}

      - name: Wait for container up
        run: sleep 5

      - name: Test container
        run: curl -f http://localhost:8080

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}/wikiguesser:${{ env.tag }}